const $=s=>document.querySelector(s),ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);let role,code,stream,pcs=new Map(),cfg={w:1280,h:720,f:30};
function send(x){if(ws.readyState===1)ws.send(JSON.stringify(x))}function status(t,on=false){$('#status').textContent=t;$('.status i').style.background=on?'#25d46d':'#e5a400'}
ws.onopen=()=>{status('Conectado',true);let c=new URLSearchParams(location.search).get('room');if(c)openModal(c.toUpperCase())};ws.onclose=()=>status('Desconectado');
function openModal(v=''){$('#input').value=v;$('#modal').classList.add('open');$('#input').focus()}function show(){ $('#room').hidden=false;$('#code').textContent=code;history.replaceState(null,'','?room='+code)}function rnd(){return Math.random().toString(36).slice(2,8).toUpperCase()}
$('#create').onclick=()=>{role='host';code=rnd();send({type:'create',code})};$('#join').onclick=()=>openModal();$('#close').onclick=()=>$('#modal').classList.remove('open');$('#go').onclick=()=>{let c=$('#input').value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(c))return alert('Digite um código de 6 caracteres.');role='viewer';code=c;send({type:'join',code:c});$('#modal').classList.remove('open')};$('#input').onkeydown=e=>e.key==='Enter'&&$('#go').click();$('#copy').onclick=()=>navigator.clipboard.writeText(code);$('#link').onclick=()=>navigator.clipboard.writeText(location.origin+'?room='+code);$('#leave').onclick=()=>location.href=location.pathname;
document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelector('.choice.active').classList.remove('active');b.classList.add('active');cfg={w:+b.dataset.w,h:+b.dataset.h,f:+b.dataset.f}});
$('#share').onclick=async()=>{if(role!=='host')return;try{stream=await navigator.mediaDevices.getDisplayMedia({video:{width:{ideal:cfg.w},height:{ideal:cfg.h},frameRate:{ideal:cfg.f,max:cfg.f}},audio:$('#audio').checked});$('#video').srcObject=stream;$('#empty').style.display='none';$('#state').textContent='Ao vivo';stream.getVideoTracks()[0].onended=stop}catch(e){alert('Compartilhamento cancelado ou bloqueado pelo navegador.')}};
function stop(){if(stream)stream.getTracks().forEach(t=>t.stop());pcs.forEach(p=>p.close());pcs.clear();stream=null;$('#video').srcObject=null;$('#empty').style.display='flex';$('#state').textContent='Aguardando'}
async function offerFor(id){let pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>e.candidate&&send({type:'ice',target:id,candidate:e.candidate});pcs.set(id,pc);let o=await pc.createOffer();await pc.setLocalDescription(o);send({type:'offer',target:id,offer:o})}
ws.onmessage=async e=>{let m=JSON.parse(e.data);if(m.type==='error')return alert(m.message);if(m.type==='created'){show();$('#state').textContent='Pronto para transmitir'}if(m.type==='joined'){show();$('#state').textContent='Conectando...'}if(m.type==='viewer-joined'&&role==='host'){ $('#count').textContent=m.count;if(stream)offerFor(m.viewerId)}if(m.type==='viewer-left'&&role==='host')$('#count').textContent=m.count||0;if(m.type==='offer'&&role==='viewer'){let pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pcs.set(m.from,pc);pc.ontrack=e=>{$('#video').srcObject=e.streams[0];$('#empty').style.display='none';$('#state').textContent='Ao vivo'};pc.onicecandidate=e=>e.candidate&&send({type:'ice',target:m.from,candidate:e.candidate});await pc.setRemoteDescription(m.offer);let a=await pc.createAnswer();await pc.setLocalDescription(a);send({type:'answer',target:m.from,answer:a})}if(m.type==='answer'){let pc=pcs.get(m.from);if(pc)await pc.setRemoteDescription(m.answer)}if(m.type==='ice'){let pc=pcs.get(m.from);if(pc)try{await pc.addIceCandidate(m.candidate)}catch{}}if(m.type==='host-left')alert('O transmissor saiu da sala.')};
